name: Linter
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')

      - name: Setup Go
        uses: actions/setup-go@v2
        #with:
        #  go-version: ${{ steps.version.outputs.go_version }}
        with:
          go-version: 1.18.0-rc1
          stable: false

      - name: golangci-lint
        #uses: golangci/golangci-lint-action@v3
        #with:
        #  version: latest
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@93a0015
          golangci-lint run ./...
