name: Prerelease
on:
  workflow_dispatch:
  push:
    branches:
      - Alpha
      - Beta
  pull_request:
    branches:
      - Alpha
      - Beta
jobs:
  Build-Prerelease:
    permissions: write-all
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set variables
        if: ${{ github.ref_name }} == Alpha
        run: echo "VERSION=master" >> $GITHUB_ENV
        shell: bash

      - name: Set variables
        if: ${{ github.ref_name }} == Beta
        run: echo "VERSION=alpha" >> $GITHUB_ENV
        shell: bash

      - name: Set ENV
        run: |
          echo "NAME=clash.meta" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "TARGET=windows/*,linux/*,darwin-10.16/*" >> $GITHUB_ENV
          echo "TAGS=with_gvisor,with_lwip" >> $GITHUB_ENV
          echo "ShortSHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
          echo "$ShortSHA"
          echo "$REPO"
        shell: bash

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          add-to-path: false

      - name: Go Test
        if: ${{github.ref_name=='Beta'}}
        run: |
          go test ./...

      - name: Set up xgo
        run: |
          docker pull techknowlogick/xgo:latest
          go install src.techknowlogick.com/xgo@latest

      - name: Build
        if: success()
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          mkdir bin
          make android-arm64
          make xgoall 
          cp release.sh ./bin/
          cd bin
          ls -la
          chmod +x *
          bash ./release.sh
          rm ./release.sh
          ls -la
          cd ..

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Prerelease-${{ github.ref_name }}
          deleteOnlyFromDrafts: false

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: Prerelease-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Alpha
        uses: softprops/action-gh-release@v1
        if: ${{  success() }}
        with:
          tag: ${{ github.ref_name }}
          tag_name: Prerelease-${{ github.ref_name }}
          files: bin/*
          prerelease: true
          generate_release_notes: true
